using System.ComponentModel;
using System.Xml.Linq;

namespace Demo_C44_G01_C_04
{
    internal class Program
    {
        static void Main(string[] args)
        {
            //#region Video 2 - Conditional Statements Examples

            //            #region Control Statements

            //            #region If Else 
            //            //Console.WriteLine("Please enter the number of the month ");
            //            //int monthNo; 
            //            //bool flag = int.TryParse(Console.ReadLine() , out monthNo );
            //            //if (monthNo == 1)
            //            //{
            //            //    Console.WriteLine("January");
            //            //    else if (monthNo == 2)
            //            //    {
            //            //        Console.WriteLine("February");
            //            //    }
            //            //    else if (monthNo == 3)
            //            //    {
            //            //        Console.WriteLine("March");
            //            //    }
            //            //    else
            //            //    {
            //            //        Console.WriteLine("invalid");
            //            //    }
            //            //}
            //            #endregion

            //            #region Switch Case
            //            //switch (monthNo)
            //            //{
            //            //    case 1:
            //            //        Console.WriteLine("January");
            //            //        break;
            //            //    case 2:
            //            //        Console.WriteLine("February");
            //            //        break;  
            //            //    case 3:
            //            //        Console.WriteLine("March");
            //            //        break;
            //            //    default:
            //            //        Console.WriteLine("invalid");
            //            //        break;  
            //            //}
            //            // Jump [ int , constant pattern ] 
            //            // jump table / branch table [data stracture ] will be generated by the compiler
            //            // better in the performance 
            //            // must the case be unique
            //            // will not create here because num of cases little
            //            /*
            //             [0] ===> Address of Action 1 
            //             [1] ===> Address of Action 2
            //             [2] ===> Address of Action 3
            //             */


            //            #endregion

            //            #endregion

            //            #region Conditional Statements - Example 2 [ Age > 22 ]

            //            //Console.WriteLine("Please enter a number  ");
            //            //int.TryParse(Console.ReadLine(), out int Age);
            //            //if (Age > 22)
            //            //{
            //            //    Console.WriteLine("Age > 22 ");
            //            //}
            //            //else if (Age < 22)
            //            //{
            //            //    Console.WriteLine("Age < 22");
            //            //}
            //            //else
            //            //{
            //            //    Console.WriteLine("Age = 22");
            //            //}

            //            //switch (Age)
            //            //{
            //            //    case (>22 ):
            //            //        Console.WriteLine("Age > 22 ");
            //            //        break;
            //            //    case (< 22):
            //            //        Console.WriteLine("Age < 22 ");
            //            //        break;
            //            //    default:
            //            //        Console.WriteLine("Age = 22");
            //            //        break;
            //            //}


            //            #endregion

            //            #region Conditional Statements - Example 3 [Name - Hello Name ]
            //            //Console.WriteLine("Please enter your name ");
            //            //string name = Console.ReadLine();
            //            //if (name == "Mariam")
            //            //{
            //            //    Console.WriteLine("Hello Mariam");
            //            //}
            //            //else if (name == "Omar")
            //            //{
            //            //    Console.WriteLine("Hello Omar");
            //            //}

            //            //else
            //            //{
            //            //    Console.WriteLine("Hello Person");
            //            //}

            //            //switch (name)
            //            //{
            //            //    case "Mariam":
            //            //        Console.WriteLine("Hello Mariam");
            //            //        break;
            //            //    case "Omar":
            //            //        Console.WriteLine("Hello Omar");
            //            //        break;
            //            //    default:
            //            //        Console.WriteLine("Hello Person");
            //            //        break;
            //            //}


            //            #endregion


            //            #region Conditional Statements - Example 4 [Budget] - [Switch with GoTo ]
            //            // 1000 ==> Option 1 
            //            // 2000 ==> Option 2 , option 1
            //            // 3000 ==> Option 3 , option 2 , option 1
            //            //Console.WriteLine("Please enter the budget ");
            //            //int.TryParse(Console.ReadLine(), out int budget);
            //            //if (budget == 1000)
            //            //{
            //            //    Console.WriteLine("Option 1");
            //            //}
            //            //else if (budget == 2000)
            //            //{
            //            //    Console.WriteLine("Option 2");
            //            //    Console.WriteLine("Option 1");
            //            //}
            //            //else if (budget == 3000)
            //            //{
            //            //    Console.WriteLine("Option 3");
            //            //    Console.WriteLine("Option 2");
            //            //    Console.WriteLine("Option 1");
            //            //}
            //            //else
            //            //{
            //            //    Console.WriteLine("Unknown Option");

            //            //}

            //            //switch (budget)
            //            //{
            //            //    case 1000:
            //            //        Console.WriteLine("Option 1");
            //            //        break;
            //            //    case 2000:
            //            //        Console.WriteLine("Option 2");
            //            //        //Console.WriteLine("Option 1");
            //            //        goto case 1000; 

            //            //    case 3000:
            //            //        Console.WriteLine("Option 3");
            //            //        //Console.WriteLine("Option 2");
            //            //        //Console.WriteLine("Option 1");
            //            //        goto case 2000;

            //            //    default:
            //            //        Console.WriteLine("Unknown Option");
            //            //        break;
            //            //}

            //            #endregion

            //            #endregion



            #region Question 1 
            /*1 - Write a program that takes a number from the user then print yes if that number can be divided by 3 and 4 otherwise print no.
                Example(1)
                Input: 12
                Output: Yes
                Example(2)
                Input: 9
                Output: No
            */

            //Console.WriteLine("please enter a number ..");

            //int number;

            //bool isParsed = int.TryParse(Console.ReadLine(), out number);


            //if (number%3 == 0 && number%4 == 0 )    
            //{
            //    Console.WriteLine("Yes");

            //}
            //else
            //{
            //    Console.WriteLine("No");
            //}


            #endregion



            #region  Question 2
            // -Write a program that allows the user to insert an integer then
            // print negative if it is negative number otherwise print positive.

            //Console.WriteLine("please enter a number ..");

            //int number;

            //bool isParsed = int.TryParse(Console.ReadLine(), out number);


            //if (number < 0)
            //{
            //    Console.WriteLine("negative");

            //}
            //else
            //{
            //    Console.WriteLine("positive");

            //}

            #endregion




            #region Question 3 
            // Write a program that takes 3 integers from the user then 
            // prints the max element and the min element.

            //Console.WriteLine(" please enter a three number ..");

            //bool isParsed1 = int.TryParse(Console.ReadLine(), out int number1);
            //bool isParsed2 = int.TryParse(Console.ReadLine(), out int number2);
            //bool isParsed3 = int.TryParse(Console.ReadLine(), out int number3);
            //int max;
            //int min;
            //max = Math.Max(Math.Max(number1, number2), number3); 
            //min = Math.Min(Math.Min(number1, number2), number3);

            //if (isParsed1 == true && isParsed2 == true && isParsed3 == true)
            //{
            //    Console.WriteLine($"Max element : {max}, Min element : {min}");
            //}
            //else
            //{
            //    Console.WriteLine("please try ag");
            //}




            #endregion




            #region Question 4
            // Write a program that allows the user to insert an integer number then check
            // If a number is even or odd

            //Console.WriteLine("please enter a number ..");

            //int checkNumber;

            //bool isParsed = int.TryParse(Console.ReadLine(), out checkNumber);


            //if (checkNumber % 2 == 0)
            //{
            //    Console.WriteLine("even");

            //}
            //else if (checkNumber % 2 == 1) 
            //{
            //    Console.WriteLine("odd");

            //}

            //else
            //{
            //    Console.WriteLine("Please try again");

            //}




            #endregion



            #region Question 5
            // Write a program that takes character from the user then if it is a vowel chars (a,e,I,o,u)
            // then print (vowel) otherwise print (consonant).

            //Console.WriteLine("please enter one character ..");
            //char characters;
            //bool isParsed = char.TryParse(Console.ReadLine(), out characters);

            //if (isParsed is true )
            //{
            //    switch (characters)
            //    {
            //        case 'a':
            //        case 'e':
            //        case 'i':
            //        case 'o':
            //        case 'u':
            //            Console.WriteLine("vowel");
            //            break;
            //        default:
            //            Console.WriteLine("consonant");
            //            break;
            //    }
            //}
            //else
            //{
            // Console.WriteLine("Please try again");
            //}





            #endregion


            #region Question 6
            //Write a program that allows the user to insert an integer then print all numbers between 1 to that number.

            //Console.WriteLine("Please enter a number ...");
            //bool isParsed = int.TryParse(Console.ReadLine(), out int number);
            //Console.Clear();

            //if (isParsed)
            //{
            //    for (int i = 1; i <= number ; i++)
            //    {
            //        Console.WriteLine(i);

            //    }
            //}
            //else
            //{
            //    Console.WriteLine("Please try again");
            //}



            #endregion


            #region Question 7

            // Write a program that allows the user to insert an integer then 
            // print a multiplication table up to 12.


            Console.WriteLine("Please enter a number ...");

            bool isParsed = int.TryParse(Console.ReadLine(), out int number);
            Console.WriteLine($"multiplication table for {number} up to 12 ");
            Console.WriteLine();

            if (isParsed)
            {
                for (int i = 1; i <= 12; i++)
                {
                    Console.WriteLine($" {number} * {i} : {i*number}");

                }
            }
            else
            {
                Console.WriteLine("Please try again");
            }


            #endregion



        }

    }

}

