
namespace Demo_C44_G01_C_04
{
    internal class Program
    {
        static void Main(string[] args)
        {
            #region Video 2 - Conditional Statements Examples

            #region Control Statements

            #region If Else 
            //Console.WriteLine("Please enter the number of the month ");
            //int monthNo; 
            //bool flag = int.TryParse(Console.ReadLine() , out monthNo );
            //if (monthNo == 1)
            //{
            //    Console.WriteLine("January");
            //    else if (monthNo == 2)
            //    {
            //        Console.WriteLine("February");
            //    }
            //    else if (monthNo == 3)
            //    {
            //        Console.WriteLine("March");
            //    }
            //    else
            //    {
            //        Console.WriteLine("invalid");
            //    }
            //}
            #endregion

            #region Switch Case
            //switch (monthNo)
            //{
            //    case 1:
            //        Console.WriteLine("January");
            //        break;
            //    case 2:
            //        Console.WriteLine("February");
            //        break;  
            //    case 3:
            //        Console.WriteLine("March");
            //        break;
            //    default:
            //        Console.WriteLine("invalid");
            //        break;  
            //}
            // Jump [ int , constant pattern ] 
            // jump table / branch table [data stracture ] will be generated by the compiler
            // better in the performance 
            // must the case be unique
            // will not create here because num of cases little
            /*
             [0] ===> Address of Action 1 
             [1] ===> Address of Action 2
             [2] ===> Address of Action 3
             */


            #endregion

            #endregion

            #region Conditional Statements - Example 2 [ Age > 22 ]

            //Console.WriteLine("Please enter a number  ");
            //int.TryParse(Console.ReadLine(), out int Age);
            //if (Age > 22)
            //{
            //    Console.WriteLine("Age > 22 ");
            //}
            //else if (Age < 22)
            //{
            //    Console.WriteLine("Age < 22");
            //}
            //else
            //{
            //    Console.WriteLine("Age = 22");
            //}

            //switch (Age)
            //{
            //    case (>22 ):
            //        Console.WriteLine("Age > 22 ");
            //        break;
            //    case (< 22):
            //        Console.WriteLine("Age < 22 ");
            //        break;
            //    default:
            //        Console.WriteLine("Age = 22");
            //        break;
            //}


            #endregion

            #region Conditional Statements - Example 3 [Name - Hello Name ]
            //Console.WriteLine("Please enter your name ");
            //string name = Console.ReadLine();
            //if (name == "Mariam")
            //{
            //    Console.WriteLine("Hello Mariam");
            //}
            //else if (name == "Omar")
            //{
            //    Console.WriteLine("Hello Omar");
            //}

            //else
            //{
            //    Console.WriteLine("Hello Person");
            //}

            //switch (name)
            //{
            //    case "Mariam":
            //        Console.WriteLine("Hello Mariam");
            //        break;
            //    case "Omar":
            //        Console.WriteLine("Hello Omar");
            //        break;
            //    default:
            //        Console.WriteLine("Hello Person");
            //        break;
            //}


            #endregion


            #region Conditional Statements - Example 4 [Budget] - [Switch with GoTo ]
            // 1000 ==> Option 1 
            // 2000 ==> Option 2 , option 1
            // 3000 ==> Option 3 , option 2 , option 1
            //Console.WriteLine("Please enter the budget ");
            //int.TryParse(Console.ReadLine(), out int budget);
            //if (budget == 1000)
            //{
            //    Console.WriteLine("Option 1");
            //}
            //else if (budget == 2000)
            //{
            //    Console.WriteLine("Option 2");
            //    Console.WriteLine("Option 1");
            //}
            //else if (budget == 3000)
            //{
            //    Console.WriteLine("Option 3");
            //    Console.WriteLine("Option 2");
            //    Console.WriteLine("Option 1");
            //}
            //else
            //{
            //    Console.WriteLine("Unknown Option");

            //}

            //switch (budget)
            //{
            //    case 1000:
            //        Console.WriteLine("Option 1");
            //        break;
            //    case 2000:
            //        Console.WriteLine("Option 2");
            //        //Console.WriteLine("Option 1");
            //        goto case 1000; 

            //    case 3000:
            //        Console.WriteLine("Option 3");
            //        //Console.WriteLine("Option 2");
            //        //Console.WriteLine("Option 1");
            //        goto case 2000;

            //    default:
            //        Console.WriteLine("Unknown Option");
            //        break;
            //}

            #endregion

            #endregion

            #region Video 3 & Switch C# 7 Pattern-Mathching When Keyword 

            #region Pattern Matching 
            ///////  object , integer , double 
            /////
            //object obj ;        // allocate 4 bytes in stack
            //obj = 10;  // Boxing
            //switch (obj)
            //{
            //    case int X :
            //        Console.WriteLine("Integer");
            //        break ;
            //    case float X :
            //        Console.WriteLine("Float");
            //        break ;
            //    case double X:
            //        Console.WriteLine("Double");
            //        break;
            //    default :
            //        Console.WriteLine("Unknown DataType");
            //        break ;
            #endregion

            #region Case Guard ( When ) 

            /////  object , integer , double 

            //object obj;        // allocate 4 bytes in stack
            //obj = 9;  // Boxing
            //switch (obj)
            //{
            //    case int X when X < 10 && X >= 5:
            //        Console.WriteLine("Integer");
            //        break;
            //    case float X:
            //        Console.WriteLine("Float");
            //        break;
            //    case double X:
            //        Console.WriteLine("Double");
            //        break;
            //    default:
            //        Console.WriteLine("Unknown DataType");
            //        break;

            #endregion

            #region User Defined Data Type 
            /// [ Person ]
            //object obj = new Person() { Id = 1 , Name = "Mariam" , Age = 20 };

            //switch(obj) {   
            //    case int input:
            //        Console.WriteLine("Integer Value ");
            //        break;
            //        case float input:
            //        Console.WriteLine("Float Value");
            //        break;
            //        case Person input when input.Name == "mariam" : Console.WriteLine("Person Value"); break;

            //    default:
            //        Console.WriteLine("Unknown Data Type");
            //        break;


            #endregion


            #endregion

            #region Video 4 Switch C# 8.0 [ Pattern Matching without alies - Switch Experssion ]

            #region Pattern Matching without alies
            // object - integer - double 
            //object obj = 10;
            //switch (obj)
            //{
            //    case int when (int)obj <= 10 :
            //        Console.WriteLine("integer");
            //        break;
            //    case float:
            //        Console.WriteLine("float");
            //        break;
            //    case double:
            //        Console.WriteLine("double");
            //        break;
            //    default: Console.WriteLine("Unknown Data Type ");
            //        break;
            #endregion


            #region Switch case before pattern matching 
            //// 1 ==> Msg = Option 1 
            //int Number;
            //string result;
            //Console.WriteLine("Please Enter the number[ 1,2,3]");
            //int.TryParse(Console.ReadLine(), out Number);
            //switch (Number)
            //{
            //    case 1:
            //        result = "Option 1";
            //        break;

            //    case 2:
            //        result = "Option 2";
            //        break;
            //    case 3:
            //        result = "Option 3";
            //        break;
            //    default:
            //        result = "Unknown Option";
            //            break; 
            //}
            #endregion



            #region Switch Expression [ Constant Pattern - discard Pattern ] 

            /// Msg = Option 1 
            //int number;
            //Console.WriteLine("Please Enter a Number ");
            //int.TryParse(Console.ReadLine(), out number);
            //string result = number switch
            //{
            //    1 => "Option 1", 
            //    2 => "Option 2", 
            //    3 => "Option 3", 
            //    _ => "Unknown Option"   // Discard Pattern 
            //};
            //Console.WriteLine(result);



            #endregion


            #region Property Pattern
            //Person person = new Person() { Id = 10, Name = "Mariam", Age = 20 };
            //string result = person switch
            //{
            //    {Age : 30} => "Age = 30 ",
            //    {Id:10 , Name : "Mariam", Age:20 } => "Hello Mariam",
            //    {Id:10 } => "Hello Mariam with id 10 ", // Property Pattern
            //    {Id:300} => "id is 300",
            //    _ => "Hello Person"
            //};
            //Console.WriteLine(result);


            #endregion


            #region Nullable type - Relational Pattern

            //    // int? = Nullable integer
            //    // int? x = null ; 
            //    int? number = null;
            //string result = number switch
            //{
            //    null => "null",
            //    int x when x > 0 => "Positive Number" , 
            //    int y when y > 0 => "Negative Number" , 
            //    _ => "Zero"
            //};
            //Console.WriteLine(result);

            #endregion


            #endregion





































        }





    }

}

