using System.ComponentModel;
using System.Xml.Linq;

namespace Demo_C44_G01_C_04
{
    internal class Program
    {
        static void Main(string[] args)
        {
            //#region Video 2 - Conditional Statements Examples

            //            #region Control Statements

            //            #region If Else 
            //            //Console.WriteLine("Please enter the number of the month ");
            //            //int monthNo; 
            //            //bool flag = int.TryParse(Console.ReadLine() , out monthNo );
            //            //if (monthNo == 1)
            //            //{
            //            //    Console.WriteLine("January");
            //            //    else if (monthNo == 2)
            //            //    {
            //            //        Console.WriteLine("February");
            //            //    }
            //            //    else if (monthNo == 3)
            //            //    {
            //            //        Console.WriteLine("March");
            //            //    }
            //            //    else
            //            //    {
            //            //        Console.WriteLine("invalid");
            //            //    }
            //            //}
            //            #endregion

            //            #region Switch Case
            //            //switch (monthNo)
            //            //{
            //            //    case 1:
            //            //        Console.WriteLine("January");
            //            //        break;
            //            //    case 2:
            //            //        Console.WriteLine("February");
            //            //        break;  
            //            //    case 3:
            //            //        Console.WriteLine("March");
            //            //        break;
            //            //    default:
            //            //        Console.WriteLine("invalid");
            //            //        break;  
            //            //}
            //            // Jump [ int , constant pattern ] 
            //            // jump table / branch table [data stracture ] will be generated by the compiler
            //            // better in the performance 
            //            // must the case be unique
            //            // will not create here because num of cases little
            //            /*
            //             [0] ===> Address of Action 1 
            //             [1] ===> Address of Action 2
            //             [2] ===> Address of Action 3
            //             */


            //            #endregion

            //            #endregion

            //            #region Conditional Statements - Example 2 [ Age > 22 ]

            //            //Console.WriteLine("Please enter a number  ");
            //            //int.TryParse(Console.ReadLine(), out int Age);
            //            //if (Age > 22)
            //            //{
            //            //    Console.WriteLine("Age > 22 ");
            //            //}
            //            //else if (Age < 22)
            //            //{
            //            //    Console.WriteLine("Age < 22");
            //            //}
            //            //else
            //            //{
            //            //    Console.WriteLine("Age = 22");
            //            //}

            //            //switch (Age)
            //            //{
            //            //    case (>22 ):
            //            //        Console.WriteLine("Age > 22 ");
            //            //        break;
            //            //    case (< 22):
            //            //        Console.WriteLine("Age < 22 ");
            //            //        break;
            //            //    default:
            //            //        Console.WriteLine("Age = 22");
            //            //        break;
            //            //}


            //            #endregion

            //            #region Conditional Statements - Example 3 [Name - Hello Name ]
            //            //Console.WriteLine("Please enter your name ");
            //            //string name = Console.ReadLine();
            //            //if (name == "Mariam")
            //            //{
            //            //    Console.WriteLine("Hello Mariam");
            //            //}
            //            //else if (name == "Omar")
            //            //{
            //            //    Console.WriteLine("Hello Omar");
            //            //}

            //            //else
            //            //{
            //            //    Console.WriteLine("Hello Person");
            //            //}

            //            //switch (name)
            //            //{
            //            //    case "Mariam":
            //            //        Console.WriteLine("Hello Mariam");
            //            //        break;
            //            //    case "Omar":
            //            //        Console.WriteLine("Hello Omar");
            //            //        break;
            //            //    default:
            //            //        Console.WriteLine("Hello Person");
            //            //        break;
            //            //}


            //            #endregion


            //            #region Conditional Statements - Example 4 [Budget] - [Switch with GoTo ]
            //            // 1000 ==> Option 1 
            //            // 2000 ==> Option 2 , option 1
            //            // 3000 ==> Option 3 , option 2 , option 1
            //            //Console.WriteLine("Please enter the budget ");
            //            //int.TryParse(Console.ReadLine(), out int budget);
            //            //if (budget == 1000)
            //            //{
            //            //    Console.WriteLine("Option 1");
            //            //}
            //            //else if (budget == 2000)
            //            //{
            //            //    Console.WriteLine("Option 2");
            //            //    Console.WriteLine("Option 1");
            //            //}
            //            //else if (budget == 3000)
            //            //{
            //            //    Console.WriteLine("Option 3");
            //            //    Console.WriteLine("Option 2");
            //            //    Console.WriteLine("Option 1");
            //            //}
            //            //else
            //            //{
            //            //    Console.WriteLine("Unknown Option");

            //            //}

            //            //switch (budget)
            //            //{
            //            //    case 1000:
            //            //        Console.WriteLine("Option 1");
            //            //        break;
            //            //    case 2000:
            //            //        Console.WriteLine("Option 2");
            //            //        //Console.WriteLine("Option 1");
            //            //        goto case 1000; 

            //            //    case 3000:
            //            //        Console.WriteLine("Option 3");
            //            //        //Console.WriteLine("Option 2");
            //            //        //Console.WriteLine("Option 1");
            //            //        goto case 2000;

            //            //    default:
            //            //        Console.WriteLine("Unknown Option");
            //            //        break;
            //            //}

            //            #endregion

            //            #endregion



            #region Question 1 
            /*1 - Write a program that takes a number from the user then print yes if that number can be divided by 3 and 4 otherwise print no.
                Example(1)
                Input: 12
                Output: Yes
                Example(2)
                Input: 9
                Output: No
            */

            //Console.WriteLine("please enter a number ..");

            //int number;

            //bool isParsed = int.TryParse(Console.ReadLine(), out number);


            //if (number%3 == 0 && number%4 == 0 )    
            //{
            //    Console.WriteLine("Yes");

            //}
            //else
            //{
            //    Console.WriteLine("No");
            //}


            #endregion



            #region  Question 2
            // -Write a program that allows the user to insert an integer then
            // print negative if it is negative number otherwise print positive.

            //Console.WriteLine("please enter a number ..");

            //int number;

            //bool isParsed = int.TryParse(Console.ReadLine(), out number);


            //if (number < 0)
            //{
            //    Console.WriteLine("negative");

            //}
            //else
            //{
            //    Console.WriteLine("positive");

            //}

            #endregion




            #region Question 3 
            // Write a program that takes 3 integers from the user then 
            // prints the max element and the min element.

            //Console.WriteLine(" please enter a three number ..");

            //bool isParsed1 = int.TryParse(Console.ReadLine(), out int number1);
            //bool isParsed2 = int.TryParse(Console.ReadLine(), out int number2);
            //bool isParsed3 = int.TryParse(Console.ReadLine(), out int number3);
            //int max;
            //int min;
            //max = Math.Max(Math.Max(number1, number2), number3); 
            //min = Math.Min(Math.Min(number1, number2), number3);

            //if (isParsed1 == true && isParsed2 == true && isParsed3 == true)
            //{
            //    Console.WriteLine($"Max element : {max}, Min element : {min}");
            //}
            //else
            //{
            //    Console.WriteLine("please try ag");
            //}




            #endregion




            #region Question 4
            // Write a program that allows the user to insert an integer number then check
            // If a number is even or odd

            //Console.WriteLine("please enter a number ..");

            //int checkNumber;

            //bool isParsed = int.TryParse(Console.ReadLine(), out checkNumber);


            //if (checkNumber % 2 == 0)
            //{
            //    Console.WriteLine("even");

            //}
            //else if (checkNumber % 2 == 1) 
            //{
            //    Console.WriteLine("odd");

            //}

            //else
            //{
            //    Console.WriteLine("Please try again");

            //}




            #endregion



            #region Question 5
            // Write a program that takes character from the user then if it is a vowel chars (a,e,I,o,u)
            // then print (vowel) otherwise print (consonant).

            //Console.WriteLine("please enter one character ..");
            //char characters;
            //bool isParsed = char.TryParse(Console.ReadLine(), out characters);

            //if (isParsed is true )
            //{
            //    switch (characters)
            //    {
            //        case 'a':
            //        case 'e':
            //        case 'i':
            //        case 'o':
            //        case 'u':
            //            Console.WriteLine("vowel");
            //            break;
            //        default:
            //            Console.WriteLine("consonant");
            //            break;
            //    }
            //}
            //else
            //{
            // Console.WriteLine("Please try again");
            //}





            #endregion


            #region Question 6
            //Write a program that allows the user to insert an integer then print all numbers between 1 to that number.

            //Console.WriteLine("Please enter a number ...");
            //bool isParsed = int.TryParse(Console.ReadLine(), out int number);
            //Console.Clear();

            //if (isParsed)
            //{
            //    for (int i = 1; i <= number ; i++)
            //    {
            //        Console.WriteLine(i);

            //    }
            //}
            //else
            //{
            //    Console.WriteLine("Please try again");
            //}



            #endregion


            #region Question 7

            // Write a program that allows the user to insert an integer then 
            // print a multiplication table up to 12.


            //Console.WriteLine("Please enter a number ...");

            //bool isParsed = int.TryParse(Console.ReadLine(), out int number);
            //Console.WriteLine($"multiplication table for {number} up to 12 ");
            //Console.WriteLine();

            //if (isParsed)
            //{
            //    for (int i = 1; i <= 12; i++)
            //    {
            //        Console.WriteLine($" {number} * {i} : {i*number}");

            //    }
            //}
            //else
            //{
            //    Console.WriteLine("Please try again");
            //}


            #endregion


            #region  Question 8
            // Write a program that allows to user to insert number then print all even numbers between 1 to this number


            //Console.WriteLine("Please enter a number ...");

            //bool isParsed = int.TryParse(Console.ReadLine(), out int number);

            //Console.Clear();

            //if (isParsed)
            //{
            //    for (int i = 1; i < number; i++)
            //    {
            //        if (i % 2 == 0)
            //        {
            //            Console.WriteLine(i);

            //        }
            //    }
            //}
            //else
            //{
            //    Console.WriteLine("Please try again");
            //}


            #endregion



            #region Question 9
            // Write a program that takes two integers then prints the power

            //Console.Write("Please enter the first integers : ");

            //bool isParsed = int.TryParse(Console.ReadLine(), out int num1);

            //Console.Write("Please enter the second integers : ");

            //bool isParsed2 = int.TryParse(Console.ReadLine(), out int num2);
            //Console.Clear();

            //int powerNumber; 

            //if (isParsed && isParsed2)
            //{
            //    for (int i = num1; i <= num2; i++)
            //    {
            //        powerNumber = i * num2; 
            //        //Console.WriteLine(i*num2);
            //        Console.Clear();
            //        Console.WriteLine(powerNumber);
            //    }
            //}
            //else
            //{
            //    Console.WriteLine("please try agian");
            //}


            #endregion



            #region Question 10
            // - Write a program to enter marks of five subjects and calculate total, average and percentage

            //Console.WriteLine("Enter Marks of five subjects: ");

            //int[] subject = new int[5];
            //int totalSubject = 0;


            //for (int i = 0 ; i < subject.Length ; i++)
            //{
            //    Console.WriteLine($"please enter the {i + 1 } subject ");

            //    int.TryParse(Console.ReadLine(), out subject[i]);
            //    totalSubject += subject[i];

            //}
            //Console.Clear();

            //Console.WriteLine($"TotalMark : {totalSubject} ");
            //Console.WriteLine($"Average Marks : {totalSubject/5}" );
            //Console.WriteLine($"Percentage : {(totalSubject * 100) / 500}");


            #endregion


            #region Question 11
            //Write a program to input the month number and print the number of days in that month.

            //Console.WriteLine("please enter month number : ");
            //;
            //bool isParsed = int.TryParse(Console.ReadLine(), out int monthNumber);
            //switch (monthNumber)
            //{
            //    case 1:
            //    case 3:
            //    case 5:
            //    case 7:
            //    case 8:
            //    case 10:
            //    case 12:
            //        Console.WriteLine("Days in Month : 31");
            //        break;

            //    case 4:
            //    case 6:
            //    case 9:
            //    case 11:
            //        Console.WriteLine("Days in Month : 30");
            //        break;

            //    case 2:
            //        Console.WriteLine("Days in Month : 28 or 29 (leap year ) ");
            //        break;
            //    default: Console.WriteLine("Please try again "); break;

            //}


            #endregion



            #region Question 12
            // Write a program to create a Simple Calculator.

            //Console.WriteLine("this is calculator");
            //Console.WriteLine("please enter the first number");
            //bool isParsing = double.TryParse(Console.ReadLine(), out double number1);

            //Console.WriteLine("please enter the operation");
            //bool isParsing3 = char.TryParse(Console.ReadLine(), out char operation);

            //Console.WriteLine("please enter the second number"); 
            //bool isParsing2= double.TryParse(Console.ReadLine(), out double number2);


            //Console.Clear();

            //switch (operation)
            //{
            //    case '+'

            //            :
            //        Console.WriteLine($"{number1}+{number2} = {number1 + number2}");
            //        break;
            //    case '-'

            //            :
            //        Console.WriteLine($"{number1}-{number2} = {number1 - number2}");
            //        break;
            //    case '*'

            //            :
            //        Console.WriteLine($"{number1}*{number2} = {number1 * number2}");
            //        break;
            //    case '/'

            //            :
            //        Console.WriteLine($"{number1}/{number2}={number1 / number2}");
            //        break;
            //    default:
            //        Console.WriteLine("please try again");
            //        break;
            //}




            #endregion






            #region  Question 13
            // - Write a program to allow the user to enter a string and print the REVERSE of it.

            //Console.WriteLine("please enter a string ");
            //string text = Console.ReadLine();
            //string reverseText = "";
            //for (int i = text.Length - 1; i >= 0; i--)
            //{
            //    reverseText += text[i];

            //}
            //Console.Clear();
            //Console.WriteLine(reverseText);


            #endregion



            #region  Question 14
            // - Write a program to allow the user to enter int and print the REVERSED of it.

            //Console.WriteLine("Please enter an integer: ");
            //string textNumber = Console.ReadLine();

            //string reversed = "";

            //for (int i = textNumber.Length - 1; i >= 0; i--)
            //{
            //    reversed += textNumber[i];
            //}

            //int reversedNumber = int.Parse(reversed);
            //Console.WriteLine("Reversed Number: " + reversedNumber);


            #endregion






            #region  Question 15
            // - Write a program in C# Sharp to find prime numbers within a range of numbers.

            //Console.Write("Enter start number of range: ");
            //int start = int.Parse(Console.ReadLine());

            //Console.Write("Enter end  number of range: ");
            //int end = int.Parse(Console.ReadLine());

            //int number = start;





            //while (number <= end)
            //{
            //    if (number > 1)
            //    {
            //        int i;
            //        for (i = 2; i <= number / 2; i++)
            //        {
            //            if ((number % i) == 0)
            //            {
            //                break;
            //            }

            //        }


            //        if (i > (number / 2))
            //        {

            //            Console.Write(number + " ");
            //        }
            //    }

            //    number++;
            //}

            #endregion





            #region  Question 16
            // - Write a program in C# Sharp to convert a decimal number into binary without using an array.

            //Console.WriteLine("Enter a decimal number : ");
            //string textNumber = Console.ReadLine();



            //for (int i = 0; i >=textNumber.Length; i++)

            //{

            // switch (textNumber[i])
            //    {

            //        case '1':
            //            textNumber.[i] = 1;
            //            break;

            //        case '2':
            //            textNumber.[i] = 10;
            //            break;
            //        case '3':
            //            textNumber.[i] = 11;
            //            break;
            //        case '4':
            //            textNumber.[i] = 100;
            //            break;
            //        case '5':
            //            textNumber.[i] = 101;
            //            break;
            //        case '6':
            //            textNumber.[i] = 110;
            //            break;
            //        case '7':
            //            textNumber.[i] = 111;
            //            break;
            //        case '8':
            //            textNumber.[i] = 1000;
            //            break;
            //        case '9':
            //            textNumber.[i] = 1001;
            //            break;
            //        case '10':
            //            textNumber.[i] = 1010;
            //            break;


            //    }

            //}

            //    int number = int.Parse(textNumber);

            //if (number == 0)
            //{
            //    Console.WriteLine($"the binary is {number} ");
            //}
            //else if (number > 0)

            //{


            //}








            #endregion




            #region  Question 17
            // - Create a program that asks the user to input three points (x1, y1), (x2, y2), and (x3, y3),
            //and determines whether these points lie on a single straight line.


            #endregion



            #region Qestion 18 
            /*
              Within a company, the efficiency of workers is evaluated based on the duration required to complete a specific task. A worker's efficiency level is determined as follows: 
            - If the worker completes the job within 2 to 3 hours, they are considered highly efficient. 
            - If the worker takes 3 to 4 hours, they are instructed to increase their speed. 
            - If the worker takes 4 to 5 hours, they are provided with training to enhance their speed. 
            - If the worker takes more than 5 hours, they are required to leave the company. 
            To calculate the efficiency of a worker, the time taken for the task is obtained via user input from the keyboard.

             */


            #endregion




            #region  Question 19
            // - Write a program that prints an identity matrix using for loop, in other words takes a value n from the user
            //  and shows the identity table of size n * n.



            #endregion




            #region Question 20
            // Write a program in C# Sharp to find the sum of all elements of the array.

            //int[]number = {10,20,30,40,50};

            //int result;
            //result = number.Sum(); 

            //Console.WriteLine($"the sum of all elements : {result} ");





            #endregion


            #region Question 21
            // Write a program in C# Sharp to merge two arrays of the same size sorted in ascending order.

            //int[] numArr1= { 10, 20, 30, 40, 50 };
            //int[] numArr2= { 60, 70, 80, 90, 100};
            //int sizeArray = numArr1.Length + numArr2.Length; 
            //int[] numMerge = new int[sizeArray];


            //for (int i = 0; i < numArr1.Length; i++)
            //{
            //    numMerge[i]+= numArr1[i];

            //}

            //for (int i = 0; i < numArr2.Length; i++)
            //{
            //    numMerge[numArr1.Length + i ]+= numArr2[i];

            //}

            //Array.Sort(numMerge);

            //for(int i = 0; i <= numMerge.Length; i++) 
            //{

            //    Console.WriteLine(numMerge[i]);
            //    Console.WriteLine();

            //}


            #endregion


            #region Question 22
            // Write a program in C# Sharp to count the frequency of each element of an array.


            //int[] numArr = { 30, 20, 30, 20, 50 };
            //int countFrequency = 0;



            //for (int i = 0; i < numArr.Length; i++)
            //{
            //    bool  isFreq = false; 

            //    for (int j = 0; j < i; j++)
            //    {
            //        if (numArr[i] == numArr[j])
            //        {
            //            isFreq = true;
            //            break;
            //        }

            //    }
            //    if (!isFreq)
            //    {
            //        int count= 0;
            //        for (int n = 0; n < numArr.Length; n++)
            //        {
            //            count++;
            //        }
            //        Console.WriteLine($"the frequency is {count} ");
            //    }
            //}






            #endregion



            #region Question 23
            // Write a program in C# Sharp to find maximum and minimum element in an array

            //int[] numArr = { 10, 90, 30, 80, 50 };
            //int maxNum = 0;
            //int minNum = 1000000;

            //for (int i = 0; i < numArr.Length; i++)
            //{
            //    if (numArr[i] > maxNum)
            //    {
            //        maxNum = numArr[i];

            //    }
            //    if (numArr[i] < minNum)
            //    { minNum = numArr[i]; }


            //}

            //Console.WriteLine($"{maxNum}  ,   {minNum}");



            // another way 

            //Array.Sort(numArr);

            //maxNum = numArr[4]; 
            //minNum = numArr[0];


            //Console.WriteLine($"{maxNum}  ,   {minNum}");



            #endregion



            #region Question 24
            // - Write a program in C# Sharp to find the second largest element in an array.
            //int[] numArr = { 10, 90, 30, 80, 50 };         
            //Array.Sort(numArr);                 // 10 - 30 - 50 - 80 - 90 
            //int sizaArray = numArr.Length;
            //Console.WriteLine(numArr[sizaArray-2 ]);





            #endregion



            #region Question 25
            // Consider an Array of Integer values with size N, having values as    





            #endregion



            #region Question 26
            // Given a list of space separated words, reverse the order of the words.

            //Console.Write("please enter the text : ");

            //string text = Console.ReadLine();
            //string[] textArray = text.Split(' '); 

            //Console.Clear();

            //for (int i = textArray.Length - 1 ; i >= 0; i--)
            //{
            //    Console.Write($"{textArray[i]} ");
            //}



            #endregion



            #region Question 27
            // Write a program to create two multidimensional arrays of same size. Accept value from user and store them in first array. Now copy all the elements of first array on second array and print second array.Write a program to create two multidimensional arrays of same size. Accept value from user and store them in first array.
            // Now copy all the elements of first array on second array and print second array.

            //int[,] theFirstarray = new int [2,3] ;  
            //int[,] theSecondarray = new int [2,3];



            //for (int i = 0; i < 2; i++)
            //{
            //    for (int j = 0; j < 3; j++)
            //    {
            //        Console.WriteLine($"please enter the element {i} , {j}");
            //        theFirstarray[i,j] = int.Parse(Console.ReadLine());
            //    }
            //}


            //for (int i = 0;i < 2; i++)
            //{
            //    for (int j = 0; j < 3; j++)
            //    {
            //        theSecondarray[i,j] = theFirstarray[i,j];
            //    }

            //}


            //Console.Clear();

            //for ( int i = 0; i <= 2; i++)
            //{
            //    for (int j = 0;j < 3; j++)
            //    {
            //        Console.WriteLine(theSecondarray[i,j]);
            //    }

            //}



            #endregion



            #region Question 28
            // Write a Program to Print One Dimensional Array in Reverse Order

            //int[] oneDiemsionalarray = { 1, 2, 3, 4, 5 };

            //Console.Write("Reverse for One Dimensional Array :-   ");

            //for (int i = oneDiemsionalarray.Length - 1; i >= 0; i--)
            //{
            //    Console.Write($" {oneDiemsionalarray[i]} ");
            //}
            //Console.WriteLine();




            #endregion



            #region Question 29

            /*
             * ⦁	.Write a program that uses the ternary operator to check if the temperature is too hot,
            too cold, or just good. Assign the result in a variable then display the result. Assume that below 10 degrees is "Just Cold",
            above 30 degrees is "Just Hot", and anything else is "Just Good".
             */







            #endregion



            #region Question 30
            // What will be the output of the C# code given below?
            /*
            int num = 1, z = 5;

            if (!(num <= 0))
                Console.WriteLine(++num + z++ + " " + ++z);
            else
                Console.WriteLine(--num + z-- + " " + --z);
            */ 

           // The output :        d. 7 7 




            #endregion





































        }

    }

}

